"""add contact_information table

Revision ID: 02e5ebf9c43c
Revises: 94ee6ab58b98
Create Date: 2026-03-09 14:19:28.609846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e5ebf9c43c'
down_revision: Union[str, Sequence[str], None] = '94ee6ab58b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emergency_number', sa.String(length=20), server_default='911', nullable=False),
    sa.Column('emergency_desc', sa.String(length=255), server_default='For life-threatening emergencies', nullable=True),
    sa.Column('phone', sa.String(length=50), server_default='', nullable=True),
    sa.Column('email', sa.String(length=255), server_default='', nullable=True),
    sa.Column('office_hours', sa.String(length=255), server_default='Monday to Friday, 8:00 AM - 5:00 PM', nullable=True),
    sa.Column('address', sa.Text(), server_default='', nullable=True),
    sa.Column('tech_support', sa.Text(), server_default='', nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_information')
    # ### end Alembic commands ###
