"""add rfid_uid to transaction_history

Revision ID: 0fa13afecfb0
Revises: a0eb1fa82d5d
Create Date: 2026-02-22 12:45:49.506741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa13afecfb0'
down_revision: Union[str, Sequence[str], None] = 'a0eb1fa82d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###