"""replace brgy_logo_path with brgy_logo bytes

Revision ID: 1844eacf67f4
Revises: 713e20fff321
Create Date: 2026-03-09 16:58:54.416790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1844eacf67f4'
down_revision: Union[str, Sequence[str], None] = '713e20fff321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_config', sa.Column('brgy_logo', sa.LargeBinary(), nullable=True))
    op.drop_column('system_config', 'brgy_logo_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_config', sa.Column('brgy_logo_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('system_config', 'brgy_logo')
    # ### end Alembic commands ###
