"""Initial schema

Revision ID: 1b523f473a40
Revises: 
Create Date: 2025-12-30 10:10:25.902686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b523f473a40'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create global_transaction_seq first
    op.execute("CREATE SEQUENCE IF NOT EXISTS global_transaction_seq")

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.SmallInteger(), nullable=False),
    sa.Column('house_no_street', sa.String(length=255), nullable=False),
    sa.Column('purok_id', sa.SmallInteger(), nullable=False),
    sa.Column('barangay', sa.String(length=64), nullable=True),
    sa.Column('municipality', sa.String(length=16), nullable=True),
    sa.Column('province', sa.String(length=16), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('resident_id', sa.SmallInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.String(length=32), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_no', sa.String(length=20), server_default=sa.text("'DR-' || LPAD(nextval('global_transaction_seq')::text, 5, '0')"), nullable=True),
    sa.Column('resident_id', sa.SmallInteger(), nullable=False),
    sa.Column('doctype_id', sa.Integer(), nullable=False),
    sa.Column('processed_by', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_file_path', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint("payment_status IN ('unpaid','paid')"),
    sa.CheckConstraint("status IN ('Pending','Approved','Ready','Released','Rejected')"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_no')
    )
    op.create_table('document_types',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('doctype_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('file', sa.Text(), nullable=True),
    sa.Column('fields', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('available_quantity', sa.Integer(), nullable=True),
    sa.Column('rate_per_day', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.CheckConstraint('available_quantity <= total_quantity'),
    sa.CheckConstraint('available_quantity >= 0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('equipment_request_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_request_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_no', sa.String(length=20), server_default=sa.text("'ER-' || LPAD(nextval('global_transaction_seq')::text, 5, '0')"), nullable=True),
    sa.Column('resident_id', sa.Integer(), nullable=True),
    sa.Column('borrower_name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('contact_number', sa.String(length=16), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('borrow_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('return_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('returned_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('total_cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('is_refunded', sa.Boolean(), nullable=True),
    sa.Column('requested_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_no')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('additional_comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('rating BETWEEN 1 AND 5'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('puroks',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('purok_name', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purok_name')
    )
    op.create_table('resident_rfid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.SmallInteger(), nullable=False),
    sa.Column('rfid_uid', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfid_uid')
    )
    op.create_table('residents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('middle_name', sa.String(length=128), nullable=True),
    sa.Column('suffix', sa.String(length=8), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('residency_start_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('rfid_pin', sa.String(length=255), nullable=True),
    sa.Column('registered_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint("gender IN ('male','female','other')"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('rfid_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rfid_reports')
    op.drop_table('residents')
    op.drop_table('resident_rfid')
    op.drop_table('puroks')
    op.drop_table('feedbacks')
    op.drop_table('equipment_requests')
    op.drop_table('equipment_request_items')
    op.drop_table('equipment_inventory')
    op.drop_table('document_types')
    op.drop_table('document_requests')
    op.drop_table('announcements')
    op.drop_table('admin')
    op.drop_table('addresses')
    # ### end Alembic commands ###
