"""add blotter records table

Revision ID: 3e81f79db19d
Revises: 4eaf22cb48b2
Create Date: 2026-02-18 02:04:45.197886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e81f79db19d'
down_revision: Union[str, Sequence[str], None] = '4eaf22cb48b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blotter_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blotter_no', sa.String(length=20), nullable=False),
    sa.Column('complainant_id', sa.Integer(), nullable=True),
    sa.Column('complainant_name', sa.String(length=255), nullable=False),
    sa.Column('complainant_age', sa.Integer(), nullable=True),
    sa.Column('complainant_address', sa.String(length=255), nullable=True),
    sa.Column('respondent_name', sa.String(length=255), nullable=False),
    sa.Column('respondent_age', sa.Integer(), nullable=True),
    sa.Column('respondent_address', sa.String(length=255), nullable=True),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('incident_time', sa.Time(), nullable=True),
    sa.Column('incident_place', sa.String(length=255), nullable=True),
    sa.Column('incident_type', sa.String(length=128), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.String(length=255), nullable=True),
    sa.Column('contact_no', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['complainant_id'], ['residents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blotter_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blotter_records')
    # ### end Alembic commands ###
