"""add_barangay_ids_and_is_id_application

Revision ID: 51d116bddaef
Revises: f824ca2a227d
Create Date: 2026-03-10 14:49:54.380473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51d116bddaef'
down_revision: Union[str, Sequence[str], None] = 'f824ca2a227d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_types', sa.Column('is_id_application', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_types', 'is_id_application')
    # ### end Alembic commands ###
