"""Add notes column to document_requests

Revision ID: 54520fc6b05e
Revises: 7cd352d92964
Create Date: 2026-01-27 17:03:58.892794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54520fc6b05e'
down_revision: Union[str, Sequence[str], None] = '7cd352d92964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_requests', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_requests', 'notes')
    # ### end Alembic commands ###
