"""add rfid_uid to transaction_history

Revision ID: 6466b8d7ccd0
Revises: 0fa13afecfb0
Create Date: 2026-02-22 12:56:57.311413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6466b8d7ccd0'
down_revision: Union[str, Sequence[str], None] = '0fa13afecfb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_name', sa.String(length=50), nullable=False),
    sa.Column('transaction_no', sa.String(length=20), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=True),
    sa.Column('rfid_uid', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_history')
    # ### end Alembic commands ###
