"""make_doctype_id_nullable

Revision ID: 65222064ac2f
Revises: bb27bb51398e
Create Date: 2026-02-25 15:57:32.265127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65222064ac2f'
down_revision: Union[str, Sequence[str], None] = 'bb27bb51398e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_requests', 'doctype_id',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_requests', 'doctype_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###
