"""add_barangay_ids_and_is_id_application

Revision ID: 65bbce623aff
Revises: 94bb78d149cd
Create Date: 2026-03-10 15:40:37.698238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65bbce623aff'
down_revision: Union[str, Sequence[str], None] = '94bb78d149cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barangay_ids', sa.Column('brgy_id_number', sa.String(length=10), nullable=True))
    op.add_column('barangay_ids', sa.Column('issued_date', sa.Date(), nullable=True))
    op.add_column('barangay_ids', sa.Column('expiration_date', sa.Date(), nullable=True))
    op.add_column('barangay_ids', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_constraint(op.f('barangay_ids_brgy_id_no_key'), 'barangay_ids', type_='unique')
    op.create_unique_constraint(None, 'barangay_ids', ['brgy_id_number'])
    op.drop_column('barangay_ids', 'expires_at')
    op.drop_column('barangay_ids', 'brgy_id_no')
    op.drop_column('barangay_ids', 'issued_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barangay_ids', sa.Column('issued_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('barangay_ids', sa.Column('brgy_id_no', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
    op.add_column('barangay_ids', sa.Column('expires_at', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'barangay_ids', type_='unique')
    op.create_unique_constraint(op.f('barangay_ids_brgy_id_no_key'), 'barangay_ids', ['brgy_id_no'], postgresql_nulls_not_distinct=False)
    op.drop_column('barangay_ids', 'created_at')
    op.drop_column('barangay_ids', 'expiration_date')
    op.drop_column('barangay_ids', 'issued_date')
    op.drop_column('barangay_ids', 'brgy_id_number')
    # ### end Alembic commands ###
