"""add system_config table

Revision ID: 713e20fff321
Revises: 02e5ebf9c43c
Create Date: 2026-03-09 14:57:39.160192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '713e20fff321'
down_revision: Union[str, Sequence[str], None] = '02e5ebf9c43c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brgy_name', sa.String(length=150), nullable=True),
    sa.Column('brgy_subname', sa.String(length=200), nullable=True),
    sa.Column('brgy_logo_path', sa.String(length=500), nullable=True),
    sa.Column('rfid_expiry_days', sa.Integer(), nullable=False),
    sa.Column('auto_logout_minutes', sa.Integer(), nullable=False),
    sa.Column('max_failed_attempts', sa.Integer(), nullable=False),
    sa.Column('lockout_minutes', sa.Integer(), nullable=False),
    sa.Column('default_view', sa.String(length=50), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('backup_schedule', sa.String(length=20), nullable=False),
    sa.Column('backup_time', sa.String(length=5), nullable=True),
    sa.Column('last_backup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_config')
    # ### end Alembic commands ###
