"""Update admin table structure pt.2

Revision ID: 7aee496413b0
Revises: bb90f65d015d
Create Date: 2026-03-04 22:24:24.306786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aee496413b0'
down_revision: Union[str, Sequence[str], None] = 'bb90f65d015d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('position', sa.String(length=100), nullable=True))
    op.add_column('admin', sa.Column('system_role', sa.String(length=50), server_default='admin', nullable=False))
    op.add_column('admin', sa.Column('photo', sa.LargeBinary(), nullable=True))
    op.drop_column('admin', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('admin', 'photo')
    op.drop_column('admin', 'system_role')
    op.drop_column('admin', 'position')
    # ### end Alembic commands ###
