"""add price to document_requests

Revision ID: 7cd352d92964
Revises: f85a0b589210
Create Date: 2026-01-26 15:55:48.383711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd352d92964'
down_revision: Union[str, Sequence[str], None] = 'f85a0b589210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_requests', sa.Column('price', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_requests', 'price')
    # ### end Alembic commands ###
