"""add_barangay_ids_and_is_id_application

Revision ID: 94bb78d149cd
Revises: 51d116bddaef
Create Date: 2026-03-10 14:50:59.700846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94bb78d149cd'
down_revision: Union[str, Sequence[str], None] = '51d116bddaef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barangay_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brgy_id_no', sa.String(length=5), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('rfid_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['document_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rfid_id'], ['resident_rfid.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brgy_id_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barangay_ids')
    # ### end Alembic commands ###
