"""Add resident photo and RFID expiration

Revision ID: a0eb1fa82d5d
Revises: 7cdee8e39b8d
Create Date: 2026-02-21 18:26:58.966207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0eb1fa82d5d'
down_revision: Union[str, Sequence[str], None] = '7cdee8e39b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resident_rfid', sa.Column('expiration_date', sa.Date(), nullable=True))
    op.add_column('residents', sa.Column('photo', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('residents', 'photo')
    op.drop_column('resident_rfid', 'expiration_date')
    # ### end Alembic commands ###
