"""add respondent_id to blotter_records

Revision ID: b9de9077e2a2
Revises: 3e81f79db19d
Create Date: 2026-02-18 03:15:12.179108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9de9077e2a2'
down_revision: Union[str, Sequence[str], None] = '3e81f79db19d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blotter_records', sa.Column('respondent_id', sa.Integer(), nullable=True))
    op.alter_column('blotter_records', 'respondent_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('blotter_records', 'incident_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_foreign_key(None, 'blotter_records', 'residents', ['respondent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blotter_records', type_='foreignkey')
    op.alter_column('blotter_records', 'incident_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('blotter_records', 'respondent_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('blotter_records', 'respondent_id')
    # ### end Alembic commands ###
