"""add event column to notifications

Revision ID: cd0cd9c894a2
Revises: eb971f964741
Create Date: 2026-03-12 15:54:56.944260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd0cd9c894a2'
down_revision: Union[str, Sequence[str], None] = 'eb971f964741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('notifications', sa.Column('event', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'event')
    # ### end Alembic commands ###
