"""add rfid_reminder_days to system_config

Revision ID: dc19c5afdc44
Revises: 65bbce623aff
Create Date: 2026-03-12 01:34:29.879067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc19c5afdc44'
down_revision: Union[str, Sequence[str], None] = '65bbce623aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('system_config', sa.Column(
        'rfid_reminder_days',
        sa.Integer(),
        nullable=False,
        server_default='30'
    ))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_config', 'rfid_reminder_days')
    # ### end Alembic commands ###
