"""add status and resolved_at to blotter_records

Revision ID: e1a96c61fd1a
Revises: fd8e06f36679
Create Date: 2026-03-16 05:33:24.724757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a96c61fd1a'
down_revision: Union[str, Sequence[str], None] = 'fd8e06f36679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blotter_records', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    op.add_column('blotter_records', sa.Column('resolved_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blotter_records', 'resolved_at')
    op.drop_column('blotter_records', 'status')
    # ### end Alembic commands ###
