"""add maintenance_message

Revision ID: f824ca2a227d
Revises: 3b20a22368e1
Create Date: 2026-03-10 11:07:57.822185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f824ca2a227d'
down_revision: Union[str, Sequence[str], None] = '3b20a22368e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_config', sa.Column('maintenance_message', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_config', 'maintenance_message')
    # ### end Alembic commands ###
