"""initial schema

Revision ID: f85a0b589210
Revises: 
Create Date: 2025-12-31 05:29:01.007529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f85a0b589210'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the global sequence FIRST
    op.execute("CREATE SEQUENCE IF NOT EXISTS global_transaction_seq START 1")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.String(length=32), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_types',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('doctype_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=True),
    sa.Column('file', sa.LargeBinary(), nullable=True),
    sa.Column('fields', sa.JSON(), server_default='[]', nullable=True),
    sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('total_quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('available_quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rate_per_day', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.CheckConstraint('available_quantity >= 0 AND available_quantity <= total_quantity', name='chk_available_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('puroks',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('purok_name', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purok_name')
    )
    op.create_table('residents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('middle_name', sa.String(length=128), nullable=True),
    sa.Column('suffix', sa.String(length=8), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('residency_start_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('rfid_pin', sa.String(length=255), nullable=True),
    sa.Column('registered_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('house_no_street', sa.String(length=255), nullable=False),
    sa.Column('purok_id', sa.SmallInteger(), nullable=False),
    sa.Column('barangay', sa.String(length=64), server_default='Poblacion Uno', nullable=True),
    sa.Column('municipality', sa.String(length=16), server_default='Amadeo', nullable=True),
    sa.Column('province', sa.String(length=16), server_default='Cavite', nullable=True),
    sa.Column('region', sa.String(length=64), server_default='Region IV-A', nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['purok_id'], ['puroks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('equipment_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_no', sa.String(length=20), server_default=sa.FetchedValue(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=True),
    sa.Column('borrower_name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('contact_number', sa.String(length=16), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='Pending', nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('borrow_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('return_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('returned_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('payment_status', sa.String(length=20), server_default='unpaid', nullable=True),
    sa.Column('is_refunded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('requested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_no')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('additional_comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resident_rfid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('rfid_uid', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfid_uid')
    )
    op.create_table('rfid_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_no', sa.String(length=20), server_default=sa.FetchedValue(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('doctype_id', sa.SmallInteger(), nullable=False),
    sa.Column('processed_by', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='Pending', nullable=False),
    sa.Column('payment_status', sa.String(length=20), server_default='unpaid', nullable=False),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_file_path', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctype_id'], ['document_types.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['admin.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_no')
    )
    op.create_table('equipment_request_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_request_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['equipment_request_id'], ['equipment_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['equipment_inventory.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment_request_items')
    op.drop_table('document_requests')
    op.drop_table('rfid_reports')
    op.drop_table('resident_rfid')
    op.drop_table('feedbacks')
    op.drop_table('equipment_requests')
    op.drop_table('admin')
    op.drop_table('addresses')
    op.drop_table('residents')
    op.drop_table('puroks')
    op.drop_table('equipment_inventory')
    op.drop_table('document_types')
    op.drop_table('announcements')
    # ### end Alembic commands ###

    # Drop the sequence at the end
    op.execute("DROP SEQUENCE IF EXISTS global_transaction_seq")