"""add sms logs table

Revision ID: fd8e06f36679
Revises: cd0cd9c894a2
Create Date: 2026-03-13 00:45:10.922254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8e06f36679'
down_revision: Union[str, Sequence[str], None] = 'cd0cd9c894a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=64), nullable=False),
    sa.Column('recipients', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sms_logs')
    # ### end Alembic commands ###
